"""Adiciona campos de venda de produto ao FluxoCaixa

Revision ID: 3d227832faa5
Revises: e82e39ae6433
Create Date: 2025-09-29 19:08:25.644521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d227832faa5'
down_revision: Union[str, None] = 'e82e39ae6433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fluxo_caixa', sa.Column('produto_id', sa.Integer(), nullable=True))
    op.add_column('fluxo_caixa', sa.Column('quantidade', sa.Integer(), server_default='1', nullable=True))
    op.add_column('fluxo_caixa', sa.Column('comissao_percentual', sa.Numeric(precision=5, scale=2), nullable=True))
    op.create_foreign_key(None, 'fluxo_caixa', 'produtos', ['produto_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fluxo_caixa', type_='foreignkey')
    op.drop_column('fluxo_caixa', 'comissao_percentual')
    op.drop_column('fluxo_caixa', 'quantidade')
    op.drop_column('fluxo_caixa', 'produto_id')
    # ### end Alembic commands ###
