"""Adiciona a tabela de produtos

Revision ID: e82e39ae6433
Revises: 
Create Date: 2025-09-29 16:48:29.562133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e82e39ae6433'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('caminho_foto', sa.String(), nullable=True),
    sa.Column('is_ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_id'), 'produtos', ['id'], unique=False)
    op.create_index(op.f('ix_produtos_nome'), 'produtos', ['nome'], unique=True)
    op.drop_index('ix_horarios_horario_disponivel', table_name='horarios')
    op.drop_index('ix_horarios_id', table_name='horarios')
    op.drop_table('horarios')
    op.drop_index('ix_profissionais_id', table_name='profissionais')
    op.drop_index('ix_profissionais_nome', table_name='profissionais')
    op.drop_table('profissionais')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profissionais',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('profissionais_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('especialidade', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='profissionais_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_profissionais_nome', 'profissionais', ['nome'], unique=False)
    op.create_index('ix_profissionais_id', 'profissionais', ['id'], unique=False)
    op.create_table('horarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('horario_disponivel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('profissional_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissionais.id'], name='horarios_profissional_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='horarios_pkey')
    )
    op.create_index('ix_horarios_id', 'horarios', ['id'], unique=False)
    op.create_index('ix_horarios_horario_disponivel', 'horarios', ['horario_disponivel'], unique=True)
    op.drop_index(op.f('ix_produtos_nome'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_id'), table_name='produtos')
    op.drop_table('produtos')
    # ### end Alembic commands ###
