"""Initial commit - recria banco limpo

Revision ID: f8101c303aa4
Revises: 
Create Date: 2026-04-20 20:00:02.186932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8101c303aa4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_index(op.f('ix_categorias_nome'), 'categorias', ['nome'], unique=True)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('whatsapp', sa.String(), nullable=True),
    sa.Column('saldo_credito', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_nome'), 'clientes', ['nome'], unique=False)
    op.create_index(op.f('ix_clientes_whatsapp'), 'clientes', ['whatsapp'], unique=True)
    op.create_table('configuracoes',
    sa.Column('chave', sa.String(), nullable=False),
    sa.Column('valor', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('chave')
    )
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.Column('senha_hash', sa.String(), nullable=True),
    sa.Column('funcao', sa.String(), nullable=False),
    sa.Column('is_ativo', sa.Boolean(), nullable=False),
    sa.Column('saldo_conta_corrente', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funcionarios_id'), 'funcionarios', ['id'], unique=False)
    op.create_index(op.f('ix_funcionarios_nome'), 'funcionarios', ['nome'], unique=False)
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('caminho_foto', sa.String(), nullable=True),
    sa.Column('is_ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_id'), 'produtos', ['id'], unique=False)
    op.create_index(op.f('ix_produtos_nome'), 'produtos', ['nome'], unique=True)
    op.create_table('bloqueios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=True),
    sa.Column('fim', sa.DateTime(), nullable=True),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bloqueios_id'), 'bloqueios', ['id'], unique=False)
    op.create_table('servicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('duracao_padrao_minutos', sa.Integer(), nullable=True),
    sa.Column('preco_minimo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_ativo', sa.Boolean(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicos_id'), 'servicos', ['id'], unique=False)
    op.create_index(op.f('ix_servicos_nome'), 'servicos', ['nome'], unique=True)
    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('duracao_efetiva_minutos', sa.Integer(), nullable=True),
    sa.Column('preco_final', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agendamentos_data_hora'), 'agendamentos', ['data_hora'], unique=False)
    op.create_index(op.f('ix_agendamentos_id'), 'agendamentos', ['id'], unique=False)
    op.create_index(op.f('ix_agendamentos_status'), 'agendamentos', ['status'], unique=False)
    op.create_table('fluxo_caixa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora_registro', sa.DateTime(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('metodo_pagamento', sa.String(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('agendamento_id', sa.Integer(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Integer(), server_default='1', nullable=True),
    sa.Column('comissao_percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamentos.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fluxo_caixa_data_hora_registro'), 'fluxo_caixa', ['data_hora_registro'], unique=False)
    op.create_index(op.f('ix_fluxo_caixa_id'), 'fluxo_caixa', ['id'], unique=False)
    op.create_index(op.f('ix_fluxo_caixa_tipo'), 'fluxo_caixa', ['tipo'], unique=False)
    op.create_table('logs_alteracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('agendamento_id', sa.Integer(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('campo_alterado', sa.String(), nullable=True),
    sa.Column('valor_antigo', sa.String(), nullable=True),
    sa.Column('valor_novo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamentos.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_alteracoes_id'), 'logs_alteracoes', ['id'], unique=False)
    op.create_table('transacoes_conta_corrente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('agendamento_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamentos.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transacoes_conta_corrente_id'), 'transacoes_conta_corrente', ['id'], unique=False)
    op.create_index(op.f('ix_transacoes_conta_corrente_tipo'), 'transacoes_conta_corrente', ['tipo'], unique=False)
    op.create_table('transacoes_credito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('agendamento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamentos.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transacoes_credito_id'), 'transacoes_credito', ['id'], unique=False)
    op.create_index(op.f('ix_transacoes_credito_tipo'), 'transacoes_credito', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transacoes_credito_tipo'), table_name='transacoes_credito')
    op.drop_index(op.f('ix_transacoes_credito_id'), table_name='transacoes_credito')
    op.drop_table('transacoes_credito')
    op.drop_index(op.f('ix_transacoes_conta_corrente_tipo'), table_name='transacoes_conta_corrente')
    op.drop_index(op.f('ix_transacoes_conta_corrente_id'), table_name='transacoes_conta_corrente')
    op.drop_table('transacoes_conta_corrente')
    op.drop_index(op.f('ix_logs_alteracoes_id'), table_name='logs_alteracoes')
    op.drop_table('logs_alteracoes')
    op.drop_index(op.f('ix_fluxo_caixa_tipo'), table_name='fluxo_caixa')
    op.drop_index(op.f('ix_fluxo_caixa_id'), table_name='fluxo_caixa')
    op.drop_index(op.f('ix_fluxo_caixa_data_hora_registro'), table_name='fluxo_caixa')
    op.drop_table('fluxo_caixa')
    op.drop_index(op.f('ix_agendamentos_status'), table_name='agendamentos')
    op.drop_index(op.f('ix_agendamentos_id'), table_name='agendamentos')
    op.drop_index(op.f('ix_agendamentos_data_hora'), table_name='agendamentos')
    op.drop_table('agendamentos')
    op.drop_index(op.f('ix_servicos_nome'), table_name='servicos')
    op.drop_index(op.f('ix_servicos_id'), table_name='servicos')
    op.drop_table('servicos')
    op.drop_index(op.f('ix_bloqueios_id'), table_name='bloqueios')
    op.drop_table('bloqueios')
    op.drop_index(op.f('ix_produtos_nome'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_id'), table_name='produtos')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_funcionarios_nome'), table_name='funcionarios')
    op.drop_index(op.f('ix_funcionarios_id'), table_name='funcionarios')
    op.drop_table('funcionarios')
    op.drop_table('configuracoes')
    op.drop_index(op.f('ix_clientes_whatsapp'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_nome'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_categorias_nome'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
