"""adiciona ondelete SET NULL em servicos categoria_id

Revision ID: ff8b2ae2b855
Revises: 328827cfe9d9
Create Date: 2026-04-25 21:39:38.797112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff8b2ae2b855'
down_revision: Union[str, None] = '328827cfe9d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('servicos_categoria_id_fkey', 'servicos', type_='foreignkey')
    op.create_foreign_key(
        'servicos_categoria_id_fkey', 'servicos', 'categorias',
        ['categoria_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('servicos_categoria_id_fkey', 'servicos', type_='foreignkey')
    op.create_foreign_key(
        'servicos_categoria_id_fkey', 'servicos', 'categorias',
        ['categoria_id'], ['id']
    )
    # ### end Alembic commands ###
